import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// ─── GitHub Pages deployment target ──────────────────────────────────────────
// These two constants drive `site`, `base`, and every GitHub link below.
// REPO must match the repository name exactly — it becomes the URL path prefix,
// and a mismatch serves a blank, unstyled page because every asset 404s.
const GITHUB_USER = 'swapnilskumbhar';
const REPO = 'InsuranceKnowledge';

// Project site → https://<user>.github.io/<repo>/  (base is required)
// For a user site (repo named <user>.github.io) set BASE = '/' instead.
const BASE = `/${REPO}`;
const REPO_URL = `https://github.com/${GITHUB_USER}/${REPO}`;
// ─────────────────────────────────────────────────────────────────────────────

export default defineConfig({
  site: `https://${GITHUB_USER}.github.io`,
  base: BASE,
  integrations: [
    starlight({
      title: 'Insurance Domain Handbook',
      description: 'Insurance domain knowledge for the people who build the systems.',
      social: [{ icon: 'github', label: 'GitHub', href: REPO_URL }],
      editLink: { baseUrl: `${REPO_URL}/edit/main/` },
      lastUpdated: true,
      customCss: [
        '@fontsource-variable/fraunces',
        '@fontsource/ibm-plex-sans/400.css',
        '@fontsource/ibm-plex-sans/500.css',
        '@fontsource/ibm-plex-sans/600.css',
        '@fontsource/ibm-plex-mono/400.css',
        '@fontsource/ibm-plex-mono/500.css',
        './src/styles/ledger.css',
      ],
      sidebar: [
        // Starlight v0.39 removed `label` + `autogenerate` as siblings; an
        // autogenerated group is now a labelled group wrapping an autogenerate item.
        { label: 'Start here', items: [{ label: 'Introduction', link: '/' }] },
        { label: 'Foundations', items: [{ autogenerate: { directory: 'foundations' } }] },
        { label: 'Ecosystem', items: [{ autogenerate: { directory: 'ecosystem' } }] },
        { label: 'Lifecycle', items: [{ autogenerate: { directory: 'lifecycle' } }] },
        { label: 'Lines of Business', items: [{ autogenerate: { directory: 'lines-of-business' } }] },
        { label: 'Systems', items: [{ autogenerate: { directory: 'systems' } }] },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
      ],
    }),
  ],
});
